# Generated by Django 5.0.2 on 2024-02-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0002_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
